- name: Scan for SSH host keys for UPENN GitLab
  local_action:
    module: shell
    cmd: ssh-keyscan upenn.bootcampcontent.com 2>/dev/null
  changed_when: False
  register: ssh_scan_upenn_gitlab

- name: Update known_hosts.
  local_action:
    module: known_hosts
    key: "{{ item }}"
    name: "upenn.bootcampcontent.com"
  with_items: "{{ ssh_scan_upenn_gitlab.stdout_lines }}"

- name: Bootcamp - Student Repo - Exists
  stat:
    path: "{{ dev }}/bootcamp/student"
  register: student_repo

- name: Bootcamp - Student Repo
  ansible.builtin.git:
    repo: git@upenn.bootcampcontent.com:upenn-bootcamp/UPENN-VIRT-FSF-PT-11-2022-U-LOLC.git
    dest: "{{ dev }}/bootcamp/student"
    key_file: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  when: student_repo.stat.exists == False

# ------------------------------------------------------------------------------------------

- name: Scan for SSH host keys for Github
  local_action:
    module: shell
    cmd: ssh-keyscan github.com 2>/dev/null
  changed_when: False
  register: ssh_scan_github

- name: Update known_hosts.
  local_action:
    module: known_hosts
    key: "{{ item }}"
    name: "github.com"
  with_items: "{{ ssh_scan_github.stdout_lines }}"

- name: Bootcamp - Instructor Repo - Exists
  stat:
    path: "{{ dev }}/bootcamp/instructor"
  register: instructor_repo

- name: Bootcamp - Instructor Repo
  ansible.builtin.git:
    repo: git@github.com:coding-boot-camp/fullstack-live.git
    dest: "{{ dev }}/bootcamp/instructor"
    key_file: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  when: instructor_repo.stat.exists == False

# ------------------------------------------------------------------------------------------
