- name: Personal - Ansible - Exists
  stat:
    path: "{{ dev }}/personal/ansible"
  register: ansible

- name: Personal - Ansible
  ansible.builtin.git:
    repo: git@github.com:DanielWGross/ansible.git
    dest: "{{ dev }}/personal/ansible"
  when: ansible.stat.exists == False
