dev: "{{ lookup('env', 'HOME') }}/dev"
homebrew_tap_apps:
  - homebrew/cask-fonts
  - heroku/brew 
homebrew_cask_apps:
  - 1password
  - alfred
  - arc
  - discord
  - elgato-camera-hub
  - elgato-control-center
  - elgato-stream-deck
  - elgato-wave-link
  - font-fira-code
  - font-fira-code-nerd-font
  - font-jetbrains-mono
  - font-montserrat
  - hey
  - insomnia
  - iterm2
  - karabiner-elements
  - rectangle-pro
  - switchresx
  - visual-studio-code
homebrew_formulae_apps:
  - heroku
  - neovim
  - ripgrep
  - tmux
  - watchman
  - yarn
