dev: "{{ lookup('env', 'HOME') }}/dev"
homebrew_tap_apps:
  - homebrew/cask-fonts
  - heroku/brew
  - mongodb/brew
homebrew_cask_apps:
  - 1password
  - alfred
  - arc
  - ddpm
  - discord
  - elgato-camera-hub
  - elgato-control-center
  - elgato-stream-deck
  - elgato-wave-link
  - font-fira-code
  - font-fira-code-nerd-font
  - font-jetbrains-mono
  - font-montserrat
  - google-chrome
  - hey
  - hyperkey
  - insomnia
  - iterm2
  # - loom
  - mongodb-compass
  # - obsidian
  - omnifocus
  - rectangle-pro
  - slack
  - switchresx
  - synologyassistant
  - visual-studio-code
  - zoom
homebrew_formulae_apps:
  # - awscli
  - heroku
  - neovim
  - opam
  - pipx
  - ripgrep
  - tmux
  - watchman
  - yarn
