- hosts: localhost
  connection: local
  vars:
    personal: "{{ lookup('env', 'HOME') }}/dev"
    bootcamp: "{{ lookup('env', 'HOME') }}/{{ personal }}/bootcamp"
  tasks:
  - import_tasks: tasks/personal-projects.yml
    # - include: tasks/homebrew.yml
