- name: Ensure .ssh Directory Exists
  file:
    dest: "{{ lookup('env', 'HOME') }}/.ssh"
    mode: 0700
    state: directory

- name: Install Private SSH Key
  copy:
    src: "{{ playbook_dir }}/ssh/id_rsa"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    mode: 0600

- name: Install Public SSH Key
  copy:
    src: "{{ playbook_dir }}/ssh/id_rsa.pub"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
    mode: 0644

