- name: Ensure .ssh Directory Exists
  file:
    dest: "{{ lookup('env', 'HOME') }}/.ssh"
    mode: 0700
    state: directory

- name: Install Private SSH Key
  copy:
    src: "{{ playbook_dir }}/ssh/id_rsa"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    mode: 0600

- name: Install Public SSH Key
  copy:
    src: "{{ playbook_dir }}/ssh/id_rsa.pub"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
    mode: 0644

- name: Scan for SSH host keys for UPENN GitLab
  local_action:
    module: shell
    cmd: ssh-keyscan upenn.bootcampcontent.com 2>/dev/null
  changed_when: False
  register: ssh_scan_upenn_gitlab

- name: Update known_hosts.
  local_action:
    module: known_hosts
    key: "{{ item }}"
    name: "upenn.bootcampcontent.com"
  with_items: "{{ ssh_scan_upenn_gitlab.stdout_lines }}"

- name: Scan for SSH host keys for Github
  local_action:
    module: shell
    cmd: ssh-keyscan github.com 2>/dev/null
  changed_when: False
  register: ssh_scan_github

- name: Update known_hosts.
  local_action:
    module: known_hosts
    key: "{{ item }}"
    name: "github.com"
  with_items: "{{ ssh_scan_github.stdout_lines }}"
